# Joystick mapping + calibration config for the native driving app.  A JoyMap
# assigns each control (steer / throttle / brake / clutch) to a joystick AXIS with
# two captured endpoints (a→0, b→1 output) and each shift/clutch to a BUTTON, so
# any stick or wheel+pedals can be made to work.  `calibrate.jl` writes the config;
# the app loads it (falling back to a default that reproduces the old hardcoded
# Logitech-Extreme-3D-Pro mapping when no config file is present).
module JoyCfg

export Ctrl, JoyMap, defaultmap, loadmap, savemap, apply

struct Ctrl
    axis::Int          # 1-based index into the GLFW axes array; 0 = unused
    a::Float64         # raw value that maps to output 0  (off / full-left)
    b::Float64         # raw value that maps to output 1  (full / full-right)
end

struct JoyMap
    steer::Ctrl
    throttle::Ctrl
    brake::Ctrl
    clutch::Ctrl       # axis 0 → use clutch_btn instead
    up_btn::Int        # 1-based button indices; 0 = unused
    dn_btn::Int
    clutch_btn::Int
    deadzone::Float64
end

"Default = the original hardcoded mapping: steer=axis1, throttle/brake=axis2 (push/
pull), buttons 1/2/3 = up/down/clutch.  `apply` then reduces to the old formulas."
defaultmap() = JoyMap(Ctrl(1, -1.0, 1.0), Ctrl(2, 0.0, -1.0), Ctrl(2, 0.0, 1.0),
                      Ctrl(0, 0.0, 1.0), 1, 2, 3, 0.06)

@inline function _norm(c::Ctrl, js)
    (c.axis < 1 || js === nothing || c.axis > length(js)) && return 0.0
    d = c.b - c.a
    abs(d) < 1e-6 ? 0.0 : (Float64(js[c.axis]) - c.a) / d
end

"""Map raw GLFW axes/buttons → (steer∈[-1,1], throttle∈[0,1], brake∈[0,1],
clutch∈[0,1], up::Bool, dn::Bool) per a JoyMap."""
function apply(m::JoyMap, js, bs)
    s = clamp(1.0 - 2.0 * _norm(m.steer, js), -1.0, 1.0)   # a=full-left→+1, b=full-right→-1
    abs(s) < m.deadzone && (s = 0.0)
    thr = clamp(_norm(m.throttle, js), 0.0, 1.0); thr < m.deadzone && (thr = 0.0)
    brk = clamp(_norm(m.brake,    js), 0.0, 1.0); brk < m.deadzone && (brk = 0.0)
    btn(i) = (bs !== nothing && i >= 1 && length(bs) >= i && bs[i] != 0)
    clu = m.clutch.axis >= 1 ? clamp(_norm(m.clutch, js), 0.0, 1.0) : (btn(m.clutch_btn) ? 1.0 : 0.0)
    (s, thr, brk, clu, btn(m.up_btn), btn(m.dn_btn))
end

# ---- file format: plain `key value` lines (a "# comment" first line is fine) ----
function savemap(path, m::JoyMap)
    open(path, "w") do io
        println(io, "# zand_racer joystick config — generated by calibrate.jl")
        for (nm, c) in (("steer",m.steer),("throttle",m.throttle),("brake",m.brake),("clutch",m.clutch))
            println(io, "$nm.axis $(c.axis)"); println(io, "$nm.a $(c.a)"); println(io, "$nm.b $(c.b)")
        end
        println(io, "up_btn $(m.up_btn)"); println(io, "dn_btn $(m.dn_btn)")
        println(io, "clutch_btn $(m.clutch_btn)"); println(io, "deadzone $(m.deadzone)")
    end
end

"""Load a JoyMap from `path`; any missing key falls back to the default."""
function loadmap(path)
    isfile(path) || return defaultmap()
    d = Dict{String,Float64}()
    for ln in eachline(path)
        s = strip(ln); (isempty(s) || startswith(s, "#")) && continue
        parts = split(s); length(parts) >= 2 || continue
        v = tryparse(Float64, parts[2]); v !== nothing && (d[parts[1]] = v)
    end
    dm = defaultmap()
    ctrl(nm, def) = Ctrl(round(Int, get(d, "$nm.axis", def.axis)),
                         get(d, "$nm.a", def.a), get(d, "$nm.b", def.b))
    JoyMap(ctrl("steer",dm.steer), ctrl("throttle",dm.throttle), ctrl("brake",dm.brake),
           ctrl("clutch",dm.clutch),
           round(Int, get(d,"up_btn",dm.up_btn)), round(Int, get(d,"dn_btn",dm.dn_btn)),
           round(Int, get(d,"clutch_btn",dm.clutch_btn)), get(d,"deadzone",dm.deadzone))
end

end # module
