[Main]
Version=True
Theater=0
Program=DTC
FalconDir=C:\Falcon BMS 4.35
FalconKey=4.35
Mission=
CamTeTrn=
TE=
Camp=
UserName=
Country=0
Airport=0
Briefing=
DataCard=
Names=0,0,0,0
SaveLoc=True
ShowTooltips=True
[DTC]
CMDS=0
HUD=0
MasterArm=0
Views=0
[PopUp]
Input=False
Ref=False
Profile=True
Bomb=True
IngressAlt=100
DiveAngle=30
Cas=500
ReleaseHeight=5000
TrackingTime=5
PullingGs=3
Turn=True
AttackHdg=0
VIPtoPUP=3
OA2toAO=0
HighLow=Low
Direction=North
Waypoint=5
[HADB]
Input=False
Version=True
Bomb=True
CAS=450
ReleaseHeight=12000
TrackingTime=5
DiveAngle=30
IngressCAS=350
PullingGs=3
Turn=Right
VRPtoPUP=3
AngleOff=60
AttackHdg=0
HighLow=60
Direction=North
Waypoint=5
[TOSS]
Input=False
Ref=False
Delivery=False
LAT=True
DiveAngle=0
IngressCAS=500
IngressHeight=9
PullingGs=3
Turn=Right
OA2toPUP=3
ReleaseAngle=30
ReleaseCAS=450
ReleaseHeight=3
AngleOff=30
AttackHdg=0
Waypoint=5
[Performance]
Apt=
Rwy=
Temp=25
Type=9
Fuel=No Tank
Loadout=0
Drag=1.0
Pitch=5
Power=0
CruiseAlt=25000
