#!/usr/bin/env python3
"""PERF-4: build demo/native/warm_statements.jl from --trace-compile logs of sim runs.

Every method Julia compiles AFTER the window is revealed is a stall the driver feels (first contact with another car:
~145 ms; a crash: ~260 ms; the first section banner, the first lap time ...). The sim marks the reveal in the trace by
calling perf4_reveal_marker(); this keeps the statements after that marker, from every log given, de-duplicated, and
writes them as a list the sim compiles during loading (drive_native_mtk.jl, PERF-4 warm-up). Statements that name a
module-internal closure (var"#...") are dropped: their names change with every edit, so they would only fail.

usage: warmgen.py OUT.jl TRACE.jl [TRACE.jl ...]
       a trace with no marker contributes nothing (say so loudly rather than guess a boundary)
"""
import re, sys

def runtime_statements(path):
    lines = open(path, encoding="utf-8", errors="replace").read().split("\n")
    mark = [i for i, l in enumerate(lines) if "perf4_reveal_marker" in l]
    if not mark:
        print(f"  {path}: NO reveal marker -- skipped", file=sys.stderr)
        return []
    out = []
    for l in lines[mark[0] + 1:]:
        l = re.sub(r"^#=\s*[0-9.]+ ms =#\s*", "", l).strip()
        if l.startswith("precompile(") and 'var"#' not in l:
            out.append(l)
    return out

def main():
    if len(sys.argv) < 3:
        print(__doc__); sys.exit(2)
    seen, keep = set(), []
    for p in sys.argv[2:]:
        st = runtime_statements(p)
        print(f"  {p}: {len(st)} runtime statements", file=sys.stderr)
        for s in st:
            if s not in seen:
                seen.add(s); keep.append(s)
    with open(sys.argv[1], "w", encoding="utf-8") as f:
        f.write("# PERF-4: methods the sim compiled AFTER its window was shown, in recorded runs -- each one was a stall\n")
        f.write("# the driver felt. Compiled during loading instead (drive_native_mtk.jl). Generated by\n")
        f.write("# JuliaMotorMTK/tools/warmgen.py from --trace-compile logs; regenerate, do not hand-edit.\n")
        for s in keep:
            f.write(s + "\n")
    print(f"  wrote {len(keep)} statements -> {sys.argv[1]}", file=sys.stderr)

if __name__ == "__main__":
    main()
